name: Feature Request
description: Suggest an idea for Smooth Scroll For Everyone
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem you're facing.
      placeholder: I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any alternative solutions or features you've thought about.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, examples from other apps, or anything else.
